name: Notify PR Conflict with Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  check-conflict:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR conflict and comment
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;

            if (!pr) {
              console.log('No PR context. This workflow must be triggered by a pull_request event.');
              return;
            }

            const prNumber = pr.number;

            // Retry loop: wait until mergeable_state is not null
            let prData, retries = 10;
            while (retries > 0) {
              const res = await github.rest.pulls.get({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: prNumber
              });
              prData = res.data;

              if (prData.mergeable_state !== null) break;

              console.log('mergeable_state not ready, retrying in 3s...');
              await new Promise(r => setTimeout(r, 3000));
              retries--;
            }

            const state = prData.mergeable_state;
            const title = prData.title;

            if (state === 'dirty') {
              const body = `⚠️ **Merge conflict detected** for PR **#${prNumber} - ${title}**.\n\nPlease resolve the conflict so this can be merged.`;

              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
            } else {
              console.log(`PR #${prNumber} is mergeable or clean (${state}). No comment posted.`);
            }
