name: Notify PR Conflict with Comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-conflict:
    runs-on: ubuntu-latest

    steps:
      - name: Wait for GitHub to calculate mergeable state
        run: sleep 10

      - name: Check PR conflict and comment
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;

            // Re-fetch PR with mergeability status
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            const state = pr.mergeable_state;
            const title = pr.title;

            if (state === 'dirty') {
              const body = `⚠️ **Merge conflict detected** for PR **#${prNumber} - ${title}**.\n\nPlease resolve the conflict so this can be merged.`;

              // Post a comment on the PR
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: prNumber,
                body: body
              });
            } else {
              console.log(`PR #${prNumber} is mergeable. No comment posted.`);
            }
